[config]
schemaVersion = "0.0.1"

[package]
namespace = "rwarazor"
name = "PegTheStreamer"
versionNumber = "1.0.1"
description = "Peg your streamer... I mean, Twitch chat integration for Peglin!"
websiteUrl = "https://github.com/Rwarazor/PegTheStreamer"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Peglin = "5.4.2100"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"
source = "./dist"
target = ""


[publish]
repository = "https://thunderstore.io"
communities = ["peglin"]
categories = []
